name: Deploy Apicurio on ECS

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TERRAFORM_STATE_NAME: ${{ secrets.TERRAFORM_STATE_NAME }}
  APICURIO_API_DOMAIN: "apicurio2.ikenna.dev"
  APICURIO_API_URL: "https://apicurio2.ikenna.dev/apis/registry/v3"
  APICURIO_UI_DOMAIN: "ui2.ikenna.dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: Create bucket in S3 cluster
        uses: aitorres/aws-s3-create-bucket@v1.2.0
        with:
          bucket-name: ${{secrets.TERRAFORM_STATE_NAME }}-cluster
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          acl: 'private'
        continue-on-error: true

      - name: Create bucket in S3 services
        uses: aitorres/aws-s3-create-bucket@v1.2.0
        with:
          bucket-name: ${{secrets.TERRAFORM_STATE_NAME }}-services
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          acl: 'private'
        continue-on-error: true

      ## Setup cluster

      - name: Envsubst s3 bucket
        working-directory: terraform/apicurio-cluster
        id: envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext moreutils
          
          if [[ $TERRAFORM_STATE_NAME == "" ]]; then
            echo "Please set TERRAFORM_STATE_NAME secret in the Github!"
            exit 127
          fi
          
          envsubst < versions.tf | sponge versions.tf
          envsubst < main.tf | sponge main.tf
        continue-on-error: false

      - name: OpenTofu fmt
        working-directory: terraform/apicurio-cluster
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        working-directory: terraform/apicurio-cluster
        id: init
        run: tofu init

      - name: OpenTofu Validate
        working-directory: terraform/apicurio-cluster
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        working-directory: terraform/apicurio-cluster
        id: plan
        run: tofu plan -no-color
        continue-on-error: false

      - name: OpenTofu Apply
        working-directory: terraform/apicurio-cluster
        id: apply
        run: tofu apply -auto-approve
        continue-on-error: false

      ## Setup services

      - name: Envsubst s3 bucket
        working-directory: terraform/services
        id: envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext moreutils

          if [[ $TERRAFORM_STATE_NAME == "" ]]; then
            echo "Please set TERRAFORM_STATE_NAME secret in the Github!"
            exit 127
          fi

          envsubst < versions.tf | sponge versions.tf
          envsubst < main.tf | sponge main.tf
        continue-on-error: false

      - name: OpenTofu fmt
        working-directory: terraform/services
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        working-directory: terraform/services
        id: init
        run: tofu init

      - name: OpenTofu Validate
        working-directory: terraform/services
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        working-directory: terraform/services
        id: plan
        run: tofu plan -no-color
        continue-on-error: false

      - name: OpenTofu Apply
        working-directory: terraform/services
        id: apply
        run: tofu apply -auto-approve
        continue-on-error: false