name: Destroy Apicurio on ECS

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEPLOYMENT_NAME: ${{ vars.AWS_DEPLOYMENT_NAME }}
  TERRAFORM_STATE_NAME: ${{ secrets.TERRAFORM_STATE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: Envsubst s3 bucket
        id: envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext moreutils
          envsubst < versions.tf | sponge versions.tf
          envsubst < main.tf | sponge main.tf
        continue-on-error: false

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Destroy
        id: destroy
        run: tofu destroy -auto-approve
        continue-on-error: false